name: C/C++ CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    
    steps:
    - uses: actions/checkout@v1
    - uses: ilammy/msvc-dev-cmd@v1.0.0
      
    - name: configure
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 16 2019" ../src
    - name: build
      run: cmake --build build --config Debug
      
    - name: archive build
      run: |
        mkdir build/VHACD
        ls build/dll
        cp build/dll/Debug/libvhacd.dll build/VHACD/libvhacd.dll
        cp build/dll/Debug/libvhacd.pdb build/VHACD/libvhacd.pdb
        cp src/dll/VHACD.cs build/VHACD/VHACD.cs
        cp src/dll/vhacd.asmdef build/VHACD/vhacd.asmdef
        cp src/dll/vhacd.asmdef.meta build/VHACD/vhacd.asmdef.meta
        cd build
        jar -cMf ${{ matrix.platform }}.zip VHACD
      
    - name: make release
      uses: actions/create-release@v1.0.0
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: true
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}

    - name: upload zip
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./build/${{ matrix.platform }}.zip
        asset_name: ${{ matrix.platform }}.zip
        asset_content_type: application/zip
